### ISSUE TITLE
Problem to install Spades in MACBOOK Pro

### ISSUE THREAD

**Issue by Fla1487** [ablab/spades#1182]
### Description of bug

As described in the issue titled, I have some troubles to install Spades in a MacBook Pro

I have used the following script:

    curl http://cab.spbu.ru/files/release3.15.5/SPAdes-3.15.5-Darwin.tar.gz -o SPAdes-3.15.5-Darwin.tar.gz
    tar -zxf SPAdes-3.15.5-Darwin.tar.gz
    cd SPAdes-3.15.5-Darwin/bin/

but I did not obtain any directory...

What is the problem?

Thank you in advance

### spades.log

-

### params.txt

-

### SPAdes version

Spades 3.15

### Operating System

M2 MAX

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Looks like the issue with your `curl`. The same link downloaded from browser without any problem. Note that curl does not follow redirects by default.

I also double checked and `wget http://cab.spbu.ru/files/release3.15.5/SPAdes-3.15.5-Darwin.tar.gz` definitely works.

**Comment by pippetingmonkey** [comment]
I have a similar problem as Fla1487 with two different Mac devices as well (Monterey 12.6.6; Ventura 13.4). Just putting my experience here in case it is helpful to Fla1487 or others who may encounter the same problem:

When I use `curl http://cab.spbu.ru/files/release3.15.5/SPAdes-3.15.5-Darwin.tar.gz -o SPAdes-3.15.5-Darwin.tar.gz`I download a file but it is empty (0 bytes). 

When I force redirect using `curl -L http://cab.spbu.ru/files/release3.15.5/SPAdes-3.15.5-Darwin.tar.gz -o SPAdes-3.15.5-Darwin.tar.gz`, I get a 77bytes file, which is too small.

I can download the file from my browser by going to http://cab.spbu.ru/files/release3.15.5/SPAdes-3.15.5-Darwin.tar.gz, after which I can install using `tar -zxf SPAdes-3.15.5-Darwin.tar.gz`, and get to the `bin` directory with all the files as expected (in fact I get more files than expected - additional files include cds-mapping-stats, cds-subgraphs, mag-improve, spades-convert-bin-to-fasta, spades-gsimplifier, spades-kmer-estimating, spades-read-filter, spades-read-filter, spades_init.py, spaligner). 

When I tried to run the test from the `bin` directory using `python3 ./spades.py --test` I couldn't complete the process as macOS couldn't verify that "spades-hammer" is free from malware and that the developer cannot be verified. It turns out that every single executable file has the same problem, so I did the low-tech method of right-clicking "open" from Finder and overriding macOS's security warning for all executable files before trying again. The test completed with warnings: 

```
======= SPAdes pipeline finished WITH WARNINGS!

=== Error correction and assembling warnings:
 * 0:00:00.571     1M / 154M  WARN    General                 (launcher.cpp              : 178)   Your data seems to have high uniform coverage depth. It is strongly recommended to use --isolate option.
```

which I don't understand since it was the test dataset... but at least the code ran. For some reason I can't run `spades.py --test` without including invoking `python3` first, perhaps that is triggering the warnings? Or because I have more files in the `bin` directory than expected? If I try to run `./spades.py --test` by itself from the `bin` directory I get the error message `env: python: No such file or directory`. Not sure if this is a problem for anyone else as well. If anyone has an explanation or a more elegant solution I'd love to hear it! Thanks!

**Comment by asl** [comment]
@pippetingmonkey Unfortunately, direct installation of binaries on MacOS (w/o AppStore or other systems like MacPorts / Brew) is quite bumpy due to additional counter-malware measures implemented by the system. So, your approach is correct: you'd need to explicitly override security settings.
