### ISSUE TITLE
finished abnormally, error code -6

### ISSUE THREAD

**Issue by jwframe28** [ablab/spades#1183]
### Description of bug

Looks like the bug is somehow related to sorting?  The scripts have been failing on a recent batch after running for ~1.5 hours

Looks like it occurs during spades hammer

### spades.log

[spades.log](https://github.com/ablab/spades/files/12611492/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/12611497/params.txt)

### SPAdes version

SPAdes 3.13.0

### Operating System

Linux HPC (debian?)

### Python Version

Python 3.6

### Method of SPAdes installation

conda (I think)

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

One of SPAdes intermediate files got corrupted. This is typically caused by some I/O problems, so I would suggest you to ask your system administrator.

In addition to this:

1. SPAdes 3.13.0 is ancient, consider upgrading to the latest SPAdes 3.15.5
2. You're only running using one CPU thread. Since SPAdes is using OpenMP consider asking your system administrator how to enable OpenMP jobs to use more that one CPU thread.

**Comment by jwframe28** [comment]
Thanks this fixed it!
