### ISSUE TITLE
except ValueError, e: when running spades from Bioconda or from pre-built binaries

### ISSUE THREAD

**Issue by senaj** [ablab/spades#172]
#Command
spades.py --test

Traceback (most recent call last):
  File "/home/jsena/anaconda3/envs/spades/bin/spades.py", line 42, in <module>
    import moleculo_postprocessing
  File "/home/jsena/anaconda3/envs/spades/share/spades-3.12.0-1/share/spades/spades_pipeline/truspades/moleculo_postprocessing.py", line 7, in <module>
    import moleculo_filter_contigs
  File "/home/jsena/anaconda3/envs/spades/share/spades-3.12.0-1/share/spades/spades_pipeline/truspades/moleculo_filter_contigs.py", line 12, in <module>
    import SeqIO
  File "/sw/compbio/biopython/build/biopython-1.61/Bio/SeqIO/__init__.py", line 312, in <module>
    from Bio.File import as_handle
  File "/sw/compbio/biopython/build/biopython-1.61/Bio/File.py", line 92
    except ValueError, e:
                     ^

##Spades version
spades                    3.12.0                        1    bioconda

**Comment by alexeigurevich** [comment]
It looks like `biopython` for Python2 is installed on your machine and added to `PYTHONPATH` environment variable. At the same time, you run SPAdes from bioconda installation for Python3 and that is causing the Syntax error.

Actually, SPAdes does not require `biopython` to run, it uses only one its submodule (`SeqIO`) which is needed for truSPAdes mode. So, we provide SeqIO file inside our own distribution and our file is compatible with both Python2 and Python3, thus normally there is no error there. However, a python module added to `PYTHONPATH` have higher priority in import statements, so in your case, the interpreter has chosen SeqIO from your own `biopython` installation rather than ours file.

To prevent this issue in the future, we made our `SeqIO` import statement more explicit, so starting from the next SPAdes release the correct file (from our package) will be chosen even if `biopython` is installed and added to `PYTHONPATH`. Currently, you can do one of the following to fix the issue (I hope any solution out of three should work, so chose the one you prefer more):
1. Remore `biopython` from `PYTHONPATH`. Or uninstall `biopython` if you don't need it.
2. Replace `biopython` for Python2 (current) with `biopython` for Python3 (you can do this with bioconda)
3. Run SPAdes using Python2 rather than Python3 (as you do now)

**Comment by senaj** [comment]
Hi alexeigurevich,

Thank you for your help! Removing Biopython from  PYTHONPATH solved my
problem.

Thanks again!
