### ISSUE TITLE
Yet another: finished abnormally, err code: -6

### ISSUE THREAD

**Issue by lavik17** [ablab/spades#217]
I've collected paired and single reads that were mapped to a metagenome-resolved bin, and I am now trying to reassemble the bin using either spades or metaspades.

I am running it on a machine with 250Gb of RAM available and 48 threads.
spades.log and params.txt are attached.

Thank you for your help!

Adi
[params.txt](https://github.com/ablab/spades/files/2622349/params.txt)
[Uploading spades.log…]()

**Comment by lavik17** [comment]
I had some progress. The error did not repeat itself when I used a larger kmer as a starting point. So no errors when using -k 41,61,81,101,121

**Comment by asl** [comment]
So, here what happened: you feed to SPAdes some arbitrary set of reads (likely corresponding to some bin of poor quality of something like this). The set consisted of ~30k paired-end reads (so unlikely to be any metagenome or even non-trivial part of it). The final assembly graphs consists of 16639 edges and almost no paired-end reads aligned to the long edges of the graph as a whole:
```
  0:01:14.069     1G / 30G   INFO    General                 (pair_info_count.cpp       : 213)   15 paired reads (0.0494641% of all) aligned to long edges
  0:01:14.114   256M / 30G   INFO    General                 (pair_info_count.cpp       : 354)     Insert size = 283.4, deviation = 170.967, left quantile = 74, right quantile = 562, read length = 151
```

This might be due to two reasons:

1. You left reads do not correspond to the right ones
2. The graph consists of just huge pile of short isolated edges
