### ISSUE TITLE
metaSPAdes, 3.13.0-Linux: finished abnormally, err code: -11

### ISSUE THREAD

**Issue by jpinus** [ablab/spades#243]
Hey there,

I tried several times metaSPAdes on an Illumina-library which is 20 GB in size.

the command line is:
`/home/jkiefe01/Software/SPAdes-3.13.0-Linux/bin/spades.py --meta --pe1-12 C_Ptru_lib_35437_74_1.inter.fastq -t 64 -o Ptru_metaSPAdes`

It worked for four other read-libraries the same size without any problems, but with this library, I always get this error:

`== Error ==  system call for: "['/gpfs/fs1/home/jkiefe01/Software/SPAdes-3.13.0-Linux/bin/spades-core', '/gpfs/fs2/project/jgu-insectsym/Ptru_Illuminas/Ptru_metaSPAdes/K33/configs/config.info', '/gpfs/fs2/project/jgu-insectsym/Ptru_Illuminas/Ptru_metaSPAdes/K33/configs/mda_mode.info', '/gpfs/fs2/project/jgu-insectsym/Ptru_Illuminas/Ptru_metaSPAdes/K33/configs/meta_mode.info']" finished abnormally, err code: -11`

[params.txt](https://github.com/ablab/spades/files/2863969/params.txt)
[spades.log](https://github.com/ablab/spades/files/2863970/spades.log)

Anyone any idea how to solve this issue or why it happend?

**Comment by asl** [comment]
Most probably the problem is due to GPFS being used as scratch storages. We saw many broken GPFS implementations. What if you'd move SPAdes scratch directory (```--tmp-dir``` option) out of GPFS?

**Comment by jpinus** [comment]
>  What if you'd move SPAdes scratch directory (`--tmp-dir` option) out of GPFS?
Unfortunately, that is not possible. It is on the HPC and the only way to use Linux. Besides the GPFS is no problem for the other runs.

**Comment by asl** [comment]
I'm afraid, you're out of luck then. GPFS is known to have broken implementation of memory mapped files and there is no workaround available.

**Comment by jpinus** [comment]
Too bad. So for these libraries, I have to go back to use KBase. Is there a way to get the GFA-File from the assembly from KBase or create it afterward?

**Comment by asl** [comment]
I have no idea what KBase is... You may want to ask them.

**Comment by cmeesters** [comment]
Hi,

> It is on the HPC and the only way to use Linux

That is not correct: The user is using our system. 

1. The user claimed that spades cannot run (well) in parallel. I successfully launched spades and observed, that - yes - it has linear code, but otherwise it, resp. hammer, runs in parallel just fine.
2. Of course, we have a (fast) scratch file system on a per job basis.

 Instead of writing what is not true, despite the fact that the user in question did follow a course in November, the user should approach as for technical issues and not file application specific issues here, on github.

Alas, the issue already has been closed (understandably so. Perhaps my message will still find its way ...

Best regards,
Christian
