### ISSUE TITLE
Assembly is finished but output scaffold file and contig file are the same

### ISSUE THREAD

**Issue by bennend** [ablab/spades#251]
Hi,

I was using MetaSpades to carry out a hybrid assembly (Illumiana + Pacbio) of metagenomics data. The assembly was finished with a warning:  ` * 5:28:22.996    67G / 116G  WARN   ScaffoldingUniqueEdgeAna (scaff_supplementary.cpp   :  59)   Less than half of genome in unique edges!`.
Also the output scaffold file and contig file are the same. Does the warning cause it ?  What parameters could i change to get the right scaffold file if that is the case? Any suggestion is appreciated.

Best,

Ben

**Comment by asl** [comment]
What is the "right scaffold file"?

Anyway, please attach your spades.log file, the telepathy module in SPAdes is in very early stage of development.

**Comment by bennend** [comment]
Hi,

Here is the log file:
[spades.log](https://github.com/ablab/spades/files/2918774/spades.log)
I thought scaffolds are longer than contigs so there should be some differences between the output scaffold file and contigs file?

**Comment by asl** [comment]
> I thought scaffolds are longer than contigs so there should be some differences between the output scaffold file and contigs file?

scaffolds might be longer than contigs, but this is not your case apparently.

Here is some preliminary analysis basing on the logs:
  - You're having reads of 150 bp length
  - Your dataset is very low covered
  - You're assembling up to k-mer length 127

As a result, already at k=77 the graph is very fragmented (because there are not that many exact k-mer overlaps). Everything is even worse at k=127. PacBio reads help a bit, they were able to close *huge* amount of coverage gaps in Illumina data:
```
4:55:09.963    29G / 116G  INFO    General                 (hybrid_aligning.cpp       : 142)   Closing gaps with long reads
5:15:00.574    66G / 116G  INFO   MultiGapJoiner           (hybrid_gap_closer.hpp     : 534)   Closed 75146 gaps
```
but they won't be able to fix all the problems. As a result, they barely aligned to the graph and therefore their usefulness for the repeat resolution is quite low given such poor quality of Illumina data.

So:
  - Do not use custom k-mers unless you're 100% sure what you're doing. Use defaults (k = 55 is your best bet here)
  - If you did any preprocessing of your reads, e.g. heavy quality trimming, coverage normalization, filtering, etc. – reconsider it, it's likely it made lots of coverage gaps

**Comment by bennend** [comment]
Thanks a lot for your detailed reply, that really helps! Thanks again!
