### ISSUE TITLE
The using of corrected.yaml

### ISSUE THREAD

**Issue by SarahIsme** [ablab/spades#274]
Dear developers,

Do you think it is necessary to use 'error-correction' function when assembling quality-filtered metagenomic reads using metaspades.py?

And could the file "corrected.yaml" of the same reads be used for the other assemble processes using different k-mers? For example, I set the k-mer as 33,55,77 and got the corrected.yaml file on the first operation.  And I used the above corrected.yaml as a intermediate file to assemble the same reads setting the k-mer as 99,121 on the second operation, so I would not spend much time on error correction.

Thanks in advance.

Sara

**Comment by asl** [comment]
Hello

> Do you think it is necessary to use 'error-correction' function when assembling quality-filtered metagenomic reads using metaspades.py?

It's hard to say for sure. Because it depends on huge range of different features including the error rate of reads, what was the quality filtering threshold and particular process (e.g. whether it was just trimming or some sliding window filtering thing, etc.).

> And could the file "corrected.yaml" of the same reads be used for the other assemble processes using different k-mers? For example, I set the k-mer as 33,55,77 and got the corrected.yaml file on the first operation.

Yes, surely. Though you need to be very careful on setting the set of k-mer lengths by yourself – you need to be 100% sure what you're doing (and 33,55,77 vs 99,121 would likely yield very different assemblies in terms of their properties).
