### ISSUE TITLE
Running With Nanopore Reads

### ISSUE THREAD

**Issue by peflanag** [ablab/spades#277]
Hi,

I'm new to using Spades. I have basecalled my fast5 files with Guppy and trimmed/demuxed with porechop. I now have a fastq file that I want to assemble but keep getting an error. Could someone tell me what I am doing wrong?

Cheers.
![Screenshot 2019-04-08 at 12 32 00](https://user-images.githubusercontent.com/32863969/55721089-55f00480-59fa-11e9-8b97-9c5bdf4dca1b.png)

**Comment by peflanag** [comment]
Actually, I'm just wondering, can ONT reads be assembled with spades or is it just for hybrid assemblies?

**Comment by asl** [comment]
From the manual (http://cab.spbu.ru/files/release3.13.0/manual.html#sec3.1):

SPAdes takes as input paired-end reads, mate-pairs and single (unpaired) reads in FASTA and FASTQ. For IonTorrent data SPAdes also supports unpaired reads in unmapped BAM format (like the one produced by Torrent Server). However, in order to run read error correction, reads should be in FASTQ or BAM format. Sanger, Oxford Nanopore and PacBio CLR reads can be provided in both formats since SPAdes does not run error correction for these types of data.

To run SPAdes 3.13.0 you need at least one library of the following types:
* Illumina paired-end/high-quality mate-pairs/unpaired reads
* IonTorrent paired-end/high-quality mate-pairs/unpaired reads
* PacBio CCS reads

Illumina and IonTorrent libraries should not be assembled together. All other types of input data are compatible. SPAdes should not be used if only PacBio CLR, Oxford Nanopore, Sanger reads or additional contigs are available.
