### ISSUE TITLE
How to check Required memory? err code: -6

### ISSUE THREAD

**Issue by Tahsin-Khan** [ablab/spades#278]
Hello, 

I am facing the issue of not having enough memory in my Error Correction stage. Is there any way to predict how much memory may be required to run the Error Correction and Meta Assembly process at default settings? 

I am attaching the Spades log and params file for your convenience. 

I tried to run the same assembly with 800 GB memory previously but the very same error occurred. 

Thanks in advance. 
[spades.log](https://github.com/ablab/spades/files/3057185/spades.log)
[params.txt](https://github.com/ablab/spades/files/3057186/params.txt)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes. At the time of crash SPAdes already used 430 Gb of RAM and your system failed to fulfill SPAdes request to allocate 73 Gb more. This is quite likely given that you set hard memory limit of 500 Gb.

Unfortunately, there is no way to predict the memory consumption before assembly since it depends on the many features of the dataset including the genome size, repeat content, strain variability, etc.
