### ISSUE TITLE
always reboot when running spade

### ISSUE THREAD

**Issue by ucassee** [ablab/spades#279]
Dear developer,
       When I use spade to assemble  my metagenome, it always reboot my system in the final step. I wonder whether there are some mistakes with my spade. Thanks in advance.
[spades.log](https://github.com/ablab/spades/files/3061838/spades.log)
[params.txt](https://github.com/ablab/spades/files/3061839/params.txt)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

You may want to look into the system log to check if there are any problems reported. I suspect there is some hardware issue here.

**Comment by mrbarbitoff** [comment]
Dear SPAdes team, 

just wanted to let you know that we are experiencing similar issues when running SPAdes v. 3.13.0 and v.3.14.1 using Windows Subsystem for Linux (WSL2) with Ubuntu 20.04 LTS (the parent OS is Windows Server 2019 Datacenter). SPAdes terminates and causes the system to reboot with no apparent dependence on the pipeline stage (sometimes the reboot occurs during error correction with hammer; sometimes, during assembly with K = 55). The error persists with both small (bacterial) and large (eukaryotic) datasets.
The log file of SPAdes does not include any error messages, the pipeline just stops and the whole systems goes into reboot. The random reboot occurs only when running SPAdes (other memory-intensive  operations like read alignment and assembly with velvet work fine on the same system). SPAdes was compiled from sources under WSL.
We have not yet checked the system log, I will post additional information in this thread FYI when it becomes available. The machine is based on an AMD Ryzen Threadripper CPU and has 256 GB of DDR4 RAM onboard.

I understand that the issue is likely to be related to hardware, but we will be grateful for any other suggestions.

**Comment by asl** [comment]
Please reopen if the problem reproduces with SPAdes 3.15.2
