### ISSUE TITLE
IonHammer - FASTQ output

### ISSUE THREAD

**Issue by spabinger** [ablab/spades#303]
Hi,

I just read your recent publication about the IonHammer tool and wanted to include it into a pipeline. However, it currently outputs FASTA files and my downstream analysis is dependent on FASTQ files.

1) Would it be possible to release a version of IonHammer with FASTQ output support?
2) Is there an easy way to convert the FASTA file back to a FASTQ file?

Thanks and best wishes,
Stephan

**Comment by asl** [comment]
Dear Stephan,

Sadly, but the answer is "no" and "no". The answer is easy though: FASTQ values in case of IonTorrent data means completely different thing as for Illumina data. In particular, they do not indicate the probability of error in a nucleotide. Instead, they correlated (but not equal to) with the probability of error of a particular homopolymer length in the reading cycle. 

Since IonHammer corrects for homopolymer errors we'd need to *infer* new quality values in case of insertions / deletions. This is well beyond the scope of IonHammer.

Now the question is how your pipeline depends on quality values. If it depends on the quality values in Illumina sense, then it is broken anyway for IonTorrent data :) In such case you may simply add dummy quality line with, say, Q40 :)
