### ISSUE TITLE
what to do after obtaining SPAdes scaffolds? - Similarly, what to do after obtaining contigs from canu?

### ISSUE THREAD

**Issue by pomidorku** [ablab/spades#346]
Hello,
I run SPAdes and obtained the scaffolds for an illumina-sequenced bacterial genome.
I did run Canu and obtained the configs for a Pacbio-sequenced bacterial genome (different from above).

The goal is to compare the sequences of several genomes (not the two above) to find out what genes are "missing"/"present" in each genome.

I spend several hours searching forums and getting some papers the recommend to read for de novo sequencing.
However, I still have not clear the following: After the first assembly, what is the next step?

I read some recommend;
1.  to polish the SPAdes-assembled genome by using Pilon and to polish the canu-assembled genome by sung Arrow.
2. Try to circularize the genomes, if possible.
3. Annotate the genomes.
4. I was also suggest to Purge Haplotigs.

Are those the recommended steps, given the goal of the assemblies I performed?

Any help will be appreciated.

Regards,

**Comment by asl** [comment]
None of the above.

There are multiple ways how one could compare the assemblies, but essentially this is outside the scope of the assembler. Usually we expect that the users know how to deal with the assembler output :)

One possibility would be to align two set of contigs agains each other and figure out what are the differences. Though, since you're having different species you'd need to deal with decent amount of differences. If you're only interested in genes, then, well, you'd need to annotate the results, extract the genes and compare the gene content. How to compare it's another question, depending on why do you need this and how different sequences you'd allow.
