### ISSUE TITLE
Phred auto-detect failing with synthetic reads

### ISSUE THREAD

**Issue by tseemann** [ablab/spades#37]
I've never had this fail before, but today it happened.
Even if the FASTQ file has 100,000 reads in it with high qualities eg. 'BDIBDIBDI' it fails.

If I force `--phred-offset 33` it works.

```
% spades.py --version
SPAdes v3.11.0

% cat bug.fq
@genome01_66313_66767_2:0:0_2:0:0_0/1
GACCTGATATTGTGTTATTCATAAATGGATTACCAGTAGTGGTAATTGAACTAAAGAATTCTACAAATGA
+
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
@genome01_3674_4142_4:1:0_2:0:0_1/1
AGTCAAAGTGCATCACTTATAGCAAAGTCGTCTACCTCAATATATTGGACACCACAATGTGGTTCTATTT
+
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
@genome01_6328_6776_6:0:0_4:0:0_2/1
TACAAGTAAAACTTGAAGATGCGATTGAATCGGACCAAACATTTGAAATGTTAATGGGTGACGTTGTCGC
+
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

% spades.py -o /tmp/bug -s #bug.fq

0:00:00.001     4M / 4M    INFO    General                 (memory_limit.hpp          :  51)   Memory limit set to 250 Gb
  0:00:00.001     4M / 4M    INFO    General                 (main.cpp                  :  93)   Trying to determine PHRED offset
  0:00:00.001     4M / 4M    ERROR   General                 (main.cpp                  :  96)   Failed to determine offset! Specify it manually and restart, please!
```

**Comment by asl** [comment]
The PHRED offset detection will fail if the variation of the quality values will not be enough to distinguish between Phred+64 and Phred+33. This means that we need to see something outside -'B'-'K' range to determine the offset unambiguously.

**Comment by tseemann** [comment]
I appreciate the quick reply, which did explain why the predictor failed, but I don't feel you gave much consideration to the problem.

Why I feel the predictor should be changed:

* Phred+64 reads are *very* rare today, especially for read lengths > 75 bp (post GAIIx).
* Some people do trim reads at >Q32 level
* The probability of seeing a high quality Phred+33 reads >> a low quality Phred+64 read

The author of Trimmomatic had the same (slightly worse) problem with his auto-detection, and he is planning to change it.

**Comment by asl** [comment]
Well. SPAdes should be able to deal with the reads with both offsets and there is already an option to explicitly force the offset, if necessary. We are feeling that it's not enough to simply warn the user in the log that the ambiguity was resolved in the particular direction. After all, if we'll decide wrong then in the majority of cases the bigger fraction of reads will be just thrown out and the results will be very bad.

Practice tells us that users rarely read warnings / errors in the logs, so the phred offset decision will go unnoticed in the majority of cases (as it was in SPAdes ~3.8 when Illumina silently changed Phred+33 format used in HiSeq X / 4000). Therefore we'd prefer to act conservative here and bail out with explicit error rather than compare probabilities.
