### ISSUE TITLE
 Failed to determine erroneous kmer threshold. Threshold set to: 22

### ISSUE THREAD

**Issue by bioramg** [ablab/spades#460]
Hi,
Thank you for developing SPAdes for hybrid assembly.

I tried to assemble Illumina pair-end with Oxford Nanopore Sequence for plant mitochondrial genome assembly. 
Before carried out, I used BBMAP to trim adapters and normalize Illumina data. I have used the commands for trim adapters:
bbmap$ ./bbduk.sh -Xmx1g in=read1.fastq in2=read2.fastq out=trim_read1.fastq out2=trim_read2.fastq ktrim=r k=23 mink=11 hdist=1 ref=resources/adapters.fa tbo tpe

for normalize:
$./bbnorm.sh in=trim_read1.fastq in2=trim_read2.fastq out=norm_read1.fastq out2=norm_rread2.fastq target=100 min=5

Then, I used these Illumina pair-end reads with Oxford nanopore and the commands as follows:
$ ./spades.py -k 99 --pe1-1 norm_read1.fastq --pe1-2 norm_read2.fastq --nanopore nano_read.fastq --careful --cov-cutoff 90 -o hybrid_assembly -m 188.

When I run using this command, I have got an error message as:
======= SPAdes pipeline finished WITH WARNINGS!

=== Error correction and assembling warnings:
 * 8:48:41.078    34G / 56G   WARN    General                 (kmer_coverage_model.cpp   : 218)   Too many erroneous kmers, the estimates might be unreliable
 * 8:48:41.472    34G / 56G   WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 22
 * 8:48:41.477    34G / 56G   WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 22

I am herewith enclosing spades.log and warning.log files for your reference. Please find and suggest me what could be the problem and how to solve it...

[spades.log](https://github.com/ablab/spades/files/4273888/spades.log)
[warnings.log](https://github.com/ablab/spades/files/4273889/warnings.log)

Thank you.
Raman. G

**Comment by asl** [comment]
The warning indicates the uneven coverage of the input data. The most likely reason for this is the "normalization". Also, using just single k-mer length might yield suboptimal results.

**Comment by bioramg** [comment]
Thank you for your kind reply.
So, what are the steps needed to be carried out? 
I already tried different k-mer lengths. I got results of kmer 21 and 33 and failed to assemble kmer 55 onwards.
Could you please suggest me to solve this issue?

**Comment by asl** [comment]
You may want to get rid of normalization. And start from the default set of k-mer length.

**Comment by bioramg** [comment]
If I use without bbmap, spades running out of memory. To reduce out of memory, I used bbmap. I would like to know what is the default set of k-mer length.

**Comment by asl** [comment]
Just do not specify the list of k-mer lengths.

**Comment by bioramg** [comment]
Thank you. I run the program without k-mer length. But it's failed after k-mer 33.

**Comment by asl** [comment]
And what was the error message?

**Comment by bioramg** [comment]
=== Error correction and assembling warnings:
 * 1:47:47.483    82G / 113G  WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 57
 * 1:47:47.494    82G / 113G  WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 57
 * 2:34:50.652    81G / 112G  WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 16
 * 2:34:50.659    81G / 112G  WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 16
 * 3:43:21.155    68G / 97G   WARN    General                 (kmer_coverage_model.cpp   : 218)   Too many erroneous kmers, the estimates might be unreliable
 * 3:43:39.815    68G / 97G   WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 8
======= Warnings saved to /home/pmslab/Desktop/Raman/Convallaria_mt/keiskei_hybrid_assembly/warnings.log

**Comment by asl** [comment]
So, it's not a failure. These are warnings indicating that the assembly results might be suboptimal

**Comment by bioramg** [comment]
== Error ==  system call for: "['/home/pmslab/Desktop/Raman/bin/bin/spades-core', '/home/pmslab/Desktop/Raman/Convallaria_mt/keiskei_hybrid_assembly/K55/configs/config.info', '/home/pmslab/Desktop/Raman/Convallaria_mt/keiskei_hybrid_assembly/K55/configs/careful_mode.inf$
======= SPAdes pipeline finished abnormally and WITH WARNINGS!

**Comment by asl** [comment]
Please provide the full spades.log as there is no error message nor the relevant information there

**Comment by bioramg** [comment]
I have got this message. I am struggling to assemble this genome for past three months. I dont know how to troubleshoot.
Thank you so much for your kind cooperation. 
[spades.log](https://github.com/ablab/spades/files/4274207/spades.log)

**Comment by asl** [comment]
You're likely running out of RAM. Worth giving SPAdes 3.14 a try

**Comment by bioramg** [comment]
ok thank you. Shall i run without using bbmap?

**Comment by asl** [comment]
You may want to skip the normalization part, yes

**Comment by bioramg** [comment]
Thank you so much for your kind reply.

**Comment by bioramg** [comment]
Dear sir,
As you suggested, I run spades after using bbmap trimming command. My server is maximum of 188 GB RAM only. How can I run this assembly?

I received error messageg like this: 

 2:05:04.864     5G / 89G   INFO    General                 (kmer_index_builder.hpp    : 150)   Merging final buckets.
  2:16:20.748     5G / 89G   INFO   K-mer Index Building     (kmer_index_builder.hpp    : 336)   Index built. Total 4941279872 bytes occupied (3.70963 bits per kmer).
  2:16:21.969     5G / 89G   ERROR  K-mer Counting           (kmer_data.cpp             : 348)   The reads contain too many k-mers to fit into available memory. You need approx. 396.971GB of free RAM to assemble your dataset


== Error ==  system call for: "['/home/pmslab/Desktop/Raman/bin/SPAdes-3.14.0-Linux/bin/spades-hammer', '/home/pmslab/Desktop/Raman/Convallaria_mt/keis_hy_asm_3_2_2020/corrected/configs/config.info']" finished abnormally, OS return value: 255

**Comment by asl** [comment]
Well, you're really out of RAM. You may want to perform heavy quality trimming / normalization with the understanding that results might be suboptimal.

**Comment by AkmalRana** [comment]
(base) akmal@akmal-pc:~/Downloads/Kh2101/Plasmid Raw reads _KH2101-new/Raw_fastq/1.Raw reads from company/new files after fast p$ spades.py -1 out_pair1.fastq -2 out_pair2.fastq -k auto -t 8 -o assemble.fasta
Command line: /usr/lib/spades/bin/spades.py	-1	/home/akmal/Downloads/Kh2101/Plasmid Raw reads _KH2101-new/Raw_fastq/1.Raw reads from company/new files after fast p/out_pair1.fastq	-2	/home/akmal/Downloads/Kh2101/Plasmid Raw reads _KH2101-new/Raw_fastq/1.Raw reads from company/new files after fast p/out_pair2.fastq	-k	auto	-t	8	-o	/home/akmal/Downloads/Kh2101/Plasmid Raw reads _KH2101-new/Raw_fastq/1.Raw reads from company/new files after fast p/assemble.fasta	

System information:
  SPAdes version: 3.13.1
  Python version: 3.8.10
  OS: Linux-5.11.0-43-generic-x86_64-with-glibc2.29

Output dir: /home/akmal/Downloads/Kh2101/Plasmid Raw reads _KH2101-new/Raw_fastq/1.Raw reads from company/new files after fast p/assemble.fasta
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home/akmal/Downloads/Kh2101/Plasmid Raw reads _KH2101-new/Raw_fastq/1.Raw reads from company/new files after fast p/out_pair1.fastq']
      right reads: ['/home/akmal/Downloads/Kh2101/Plasmid Raw reads _KH2101-new/Raw_fastq/1.Raw reads from company/new files after fast p/out_pair2.fastq']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /home/akmal/Downloads/Kh2101/Plasmid Raw reads _KH2101-new/Raw_fastq/1.Raw reads from company/new files after fast p/assemble.fasta/tmp
  Threads: 8
  Memory limit (in Gb): 7


======= SPAdes pipeline started. Log can be found here: /home/akmal/Downloads/Kh2101/Plasmid Raw reads _KH2101-new/Raw_fastq/1.Raw reads from company/new files after fast p/assemble.fasta/spades.log


===== Read error correction started. 


== Running read error correction tool: /usr/lib/spades/bin/spades-hammer /home/akmal/Downloads/Kh2101/Plasmid Raw reads _KH2101-new/Raw_fastq/1.Raw reads from company/new files after fast p/assemble.fasta/corrected/configs/config.info

  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  75)   Starting BayesHammer, built from N/A, git revision N/A
  0:00:00.001     4M / 4M    INFO    General                 (main.cpp                  :  76)   Loading config from /home/akmal/Downloads/Kh2101/Plasmid Raw reads _KH2101-new/Raw_fastq/1.Raw reads from company/new files after fast p/assemble.fasta/corrected/configs/config.info
  0:00:00.002     4M / 4M    INFO    General                 (main.cpp                  :  78)   Maximum # of threads to use (adjusted due to OMP capabilities): 1
  0:00:00.002     4M / 4M    INFO    General                 (memory_limit.cpp          :  49)   Memory limit set to 7 Gb
  0:00:00.002     4M / 4M    INFO    General                 (main.cpp                  :  86)   Trying to determine PHRED offset
  0:00:00.002     4M / 4M    INFO    General                 (main.cpp                  :  92)   Determined value is 33
  0:00:00.002     4M / 4M    INFO    General                 (hammer_tools.cpp          :  36)   Hamming graph threshold tau=1, k=21, subkmer positions = [ 0 10 ]
  0:00:00.002     4M / 4M    INFO    General                 (main.cpp                  : 113)   Size of aux. kmer data 24 bytes
     === ITERATION 0 begins ===
  0:00:00.003     4M / 4M    INFO   K-mer Index Building     (kmer_index_builder.hpp    : 301)   Building kmer index
  0:00:00.006     4M / 4M    INFO    General                 (kmer_index_builder.hpp    : 117)   Splitting kmer instances into 16 files using 1 threads. This might take a while.
  0:00:00.006     4M / 4M    INFO    General                 (file_limit.hpp            :  32)   Open file limit set to 1024
  0:00:00.006     4M / 4M    INFO    General                 (kmer_splitters.hpp        :  89)   Memory available for splitting buffers: 2.33203 Gb
  0:00:00.006     4M / 4M    INFO    General                 (kmer_splitters.hpp        :  97)   Using cell size of 4194304
  0:00:00.006   580M / 616M  INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /home/akmal/Downloads/Kh2101/Plasmid Raw reads _KH2101-new/Raw_fastq/1.Raw reads from company/new files after fast p/out_pair1.fastq
  0:00:08.294   580M / 616M  INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 186442 reads
  0:00:16.235   580M / 616M  INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 372757 reads
  0:00:24.209   580M / 616M  INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 559499 reads
  0:00:32.277   580M / 616M  INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 745886 reads
  0:00:40.179   580M / 616M  INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 932341 reads
  0:00:48.069   580M / 616M  INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 1118891 reads
  0:01:37.407   580M / 616M  INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 2247109 reads
  0:03:06.012   580M / 616M  INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 4317248 reads
  0:05:04.642   580M / 616M  INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /home/akmal/Downloads/Kh2101/Plasmid Raw reads _KH2101-new/Raw_fastq/1.Raw reads from company/new files after fast p/out_pair2.fastq
  0:06:03.015   580M / 616M  INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 8431840 reads
  0:10:23.841   580M / 616M  INFO   K-mer Splitting          (kmer_data.cpp             : 112)   Total 14214996 reads processed
  0:10:23.857     4M / 616M  INFO    General                 (kmer_index_builder.hpp    : 120)   Starting k-mer counting.
  0:12:02.017     4M / 616M  INFO    General                 (kmer_index_builder.hpp    : 127)   K-mer counting done. There are 609950672 kmers in total.
  0:12:02.017     4M / 616M  INFO    General                 (kmer_index_builder.hpp    : 133)   Merging temporary buckets.
  0:12:06.445     4M / 616M  INFO   K-mer Index Building     (kmer_index_builder.hpp    : 314)   Building perfect hash indices
  0:13:49.516   320M / 616M  INFO    General                 (kmer_index_builder.hpp    : 150)   Merging final buckets.
  0:14:00.469   320M / 616M  INFO   K-mer Index Building     (kmer_index_builder.hpp    : 336)   Index built. Total 282849874 bytes occupied (3.70981 bits per kmer).
  0:14:00.470   320M / 616M  ERROR  K-mer Counting           (kmer_data.cpp             : 351)   The reads contain too many k-mers to fit into available memory. You need approx. 22.7224GB of free RAM to assemble your dataset


== Error ==  system call for: "['/usr/lib/spades/bin/spades-hammer', '/home/akmal/Downloads/Kh2101/Plasmid Raw reads _KH2101-new/Raw_fastq/1.Raw reads from company/new files after fast p/assemble.fasta/corrected/configs/config.info']" finished abnormally, err code: 255

I am getting this error. Can you Please guide me?

**Comment by asl** [comment]
@AkmalRana Please do not hijack old closed issues. In your case log clearly reads:
```
0:14:00.470 320M / 616M ERROR K-mer Counting (kmer_data.cpp : 351) The reads contain too many k-mers to fit into available memory. You need approx. 22.7224GB of free RAM to assemble your dataset
```

**Comment by AkmalRana** [comment]
@asl Sorry for this trouble.

**Comment by asmlgkj** [comment]
@asl 
Thanks a lot.
 I met the same error, mine sample is ctdna human sample,
the error is
=== Error correction and assembling warnings:
 * 0:00:33.645   611M / 3386M WARN    General                 (kmer_coverage_model.cpp   : 218)   Too many erroneous kmers, the estimates might be unreliable
 * 0:00:54.182   591M / 2711M WARN    General                 (pair_info_count.cpp       : 376)   Estimated mean insert size 101.664 is very small compared to read length 149
======= Warnings saved to  result/warnings.log

**Comment by asl** [comment]
@asmlgkj As it was written above – please do not hijack old issue. Open new

**Comment by asmlgkj** [comment]
@asl sorry , I failed to undertand the word hijack

**Comment by luu520** [comment]
So, when I encounter the following warnings, can I ignore these warnings and proceed with the next step of analysis using the assembly results? Thanks for your help.

> === Error correction and assembling warnings:
> 
> * 1:47:47.483    82G / 113G  WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 57
> * 1:47:47.494    82G / 113G  WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 57
> * 2:34:50.652    81G / 112G  WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 16
> * 2:34:50.659    81G / 112G  WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 16
> * 3:43:21.155    68G / 97G   WARN    General                 (kmer_coverage_model.cpp   : 218)   Too many erroneous kmers, the estimates might be unreliable
> * 3:43:39.815    68G / 97G   WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 8
>   ======= Warnings saved to /home/pmslab/Desktop/Raman/Convallaria_mt/keiskei_hybrid_assembly/warnings.log
