### ISSUE TITLE
Spades 3.14.1 MacOS and Linux different contigs count.

### ISSUE THREAD

**Issue by mmaesaar** [ablab/spades#507]
When running spades 3.14.1 in MacOS I get 39 contigs but in Linux I get 40 contigs with same parameters and same trimmed fastq paired sequences.

Is it normal behaviour?

Thank you

**Comment by asl** [comment]
Hello

Will you please provide spades.log files from the both runs?

**Comment by mmaesaar** [comment]
[spades_MAC.log](https://github.com/ablab/spades/files/4649931/spades_MAC.log)
[spades_LINUX.log](https://github.com/ablab/spades/files/4649932/spades_LINUX.log)

**Comment by asl** [comment]
Ok, so this is what happened: the results of read error correction is slightly different. This is something expected as heavy floating point math is involved and there might be slight differences due to FP rounding, compiler optimizations, etc. As a result, the overall assembly pipeline runs a bit differently and therefore different results are obtained. As far as I can see, the top 10 contigs are similar, so you should be fine.

**Comment by mmaesaar** [comment]
@asl so using MacOS output over Linux is fine?
