### ISSUE TITLE
err code: -5

### ISSUE THREAD

**Issue by marybelsoto** [ablab/spades#51]
Hi there,

I don't believe there's a past issue regarding the error message I get when I run the test dataset. Here are two of the output files.

[params.txt](https://github.com/ablab/spades/files/1513711/params.txt)
[spades.log](https://github.com/ablab/spades/files/1513712/spades.log)

Any help with this would be greatly appreciated. Thanks,
Marybel

**Comment by asl** [comment]
Hello

Let's read the log file:

dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib
  Referenced from: /usr/local/Cellar/spades/3.11.0/bin/hammer
  Reason: image not found

So, it seems that your SPAdes installation is broken. You may want to ask Homebrew folks about this since we do not maintain this installation path.
