### ISSUE TITLE
Guidance: rnaSPAdes or metaviralSPAdes for coronavirus genome?

### ISSUE THREAD

**Issue by taltman** [ablab/spades#516]
To the SPAdes dev team:

I'm a long-time fan of the SPAdes assembler, and I'm hoping that I can get some guidance on how to best make use of your suite of tools for my given problem. 

I am interested in trying to isolate single-stranded RNA virus genomes (like SARS-CoV-2) from meta-transcriptome RNAseq datasets with host (& prokaryote) reads mixed in. The target genome is in the ~30kbp range. Do you recommend using `rnaspades`, or `metaviralspades` for this task? 

Thank you!

**Comment by Dmitry-Antipov** [comment]
Hi. Mostly likely any SPAdes family tool will work.
I myself would start with just SPAdes (with --careful option). 
It's not exactly the case metaviralSPAdes was designed for, but it may also help. metaSPAdes is also an option. rnaSPAdes is less suitable for viral RNA since it will probably make fake "isoforms" from sequencing errors.
Also, if you have really high coverage (>1000x) of this virus, it can be useful to add --cov-cutoff 20 option
If you'll see any troubles with this data we'll be glad to help you.

**Comment by taltman** [comment]
Thank you for providing that guidance, @Dmitry-Antipov ! I will follow your advice, and will let you know if we have any difficulties.

Just out of curiosity, what is it about the coronavirus scenario that is not perfectly suited for metaviralSPAdes? Was it designed more with DNA viruses in mind?

**Comment by sjackman** [comment]
> rnaSPAdes is less suitable for viral RNA since it will probably make fake "isoforms" from sequencing errors.

How would the sequencing errors in the viral RNA be different in behaviour than the sequencing errors in the human transcripts?

**Comment by Dmitry-Antipov** [comment]
> Was it designed more with DNA viruses in mind?
Yes.
Also, metaviralSPAdes improves on baseline in case when you have multiple relative viral species in one sample. This can lead to  tangled assembly graph and complicates assembly. If you have only one virus - it is not the case.

Speaking on exactly sars-cov-2 I would consider reference-based approaches instead of de novo assembly.

>How would the sequencing errors in the viral RNA be different in behaviour than the sequencing errors in the human transcripts?
rnaSPAdes removes less bulges than other SPAdes family tools because some of the bulges  can represent an alternative splicing event. Moreover, during repeat resolution stage such bulges leads to multiple fake(in case of viral RNA) "isoforms" and so, high duplication ratio.
This is not the common issue in case of "normal" coverage. But in some sars-cov-2 datasets we  see >10000x read coverage.

**Comment by taltman** [comment]
@Dmitry-Antipov Thank you for your detailed reply. To provide you with more context, @sjackman and I are working on a project with others called Serratus that is searching for remote members of the Coronavirus clade; not just SARS-CoV-2 isolates:

https://github.com/ababaian/serratus

The high divergence is driving the need for de novo assembly.

**Comment by sjackman** [comment]
> I myself would start with just SPAdes (with --careful option).

Would SPAdes handle the wide dynamic range of RNA expression, that is, depth of coverage? If the RNA virus is at 50x depth of coverage, but other host transcripts are at 100x, 1,000x, or 10,000x, would you expect the RNA virus to assemble with SPAdes?

> rnaSPAdes removes less bulges than other SPAdes family tools because some of the bulges can represent an alternative splicing event.

Is there a parameter to make the bulge smoothing (bubble popping) of rnaSPAdes more aggressive?

**Comment by Dmitry-Antipov** [comment]
@andrewprzh , we need you here!

**Comment by andrewprzh** [comment]
> Would SPAdes handle the wide dynamic range of RNA expression, that is, depth of coverage? If the RNA virus is at 50x depth of coverage, but other host transcripts are at 100x, 1,000x, or 10,000x, would you expect the RNA virus to assemble with SPAdes?
My guess is that you may try to set `--cov-cutoff` option to "off" or some small value. In SPAdes it's "auto" by default and may give unexpected number on RNA-Seq data (most probably also small one). MetaSPAdes and rnaSPAdes have coverage cut-off turned off by default.

>Is there a parameter to make the bulge smoothing (bubble popping) of rnaSPAdes more aggressive?
There is no implicit parameter, unfortunately. Most of the parameters are specified in the internal configs and can be edited. 
By default, rnaSPAdes should remove most of the bulges caused by SNPs or short indel, but keep those that originate for alternative exon inclusion/exclusion (i.e. bulges with similar lengths are removed). We have seen some odd cases for super-high-coverage sequences, we'll try to figure it out soon.

**Comment by andrewprzh** [comment]
My bad, `--cov-cutoff` is off by default, so should be ok with default settings. By OK I mean that the viral sequence would be assembled somehow and most likely not thrown away. Not sure about the rest of the data though.

**Comment by asl** [comment]
Serratus is using coronaSPAdes :)
