### ISSUE TITLE
rnaSPAdes - poly-N stretches in assembly of strand-specific data

### ISSUE THREAD

**Issue by lmuenter** [ablab/spades#566]
Hello,

This problem has been reported [earlier](https://github.com/ablab/spades/issues/141), but I also encountered it in the current version of rnaspades (spades version 3.14).  Sorry for first posting in the old thread!

During assembly of strand-specific RNA-seq data, poly-N stretches are introduced.
Roughly 50,000 of a total 200,000 contigs contain poly-N stretches of ca. 3-15, sometimes even 30 nt! This problem only occurs in strand-specific mode.
I assembled strand-specific RNAseq-data (TruSeq) from a polyploid plant with the command:

> rnaspades.py -o "$outdir" --ss-rf --dataset "$samplesFile" -m "$max_memory" -t "$threads"

Interestingly, the transrate score was still high at 0.39 - 0.45 (raw - optimised) and the assemblies were essentially BUSCO-complete (only 2% of empryhophyte BUSCOs were missing). Using Salmon, a mapping rate of 96% was found, and the library type was guessed correctly as "ISR" (via --libtype A).

However, as previously predicted in the old thread, the relative ORF-lengths were substantially decreased compared to a simple paired-end assembly with the same data (ORF-lengths were 52% vs 65% of total transcript lengths).

Could this be a bug with the dataset file? Might there be biological reasons for this behaviour (high transcriptomic complexity...)?

However, thank you so much for this program, it has otherwise worked like a charm!

*PS:*
The dataset-file I used (In yaml format, but with a .txt extension, since github seemingly does not allow upload of .yaml-files):

[samples_list.txt](https://github.com/ablab/spades/files/5155851/samples_list.txt)

**Comment by andrewprzh** [comment]
Hello, sorry for a delay.

You report is slightly surprising, since strand-specific mode has only a few additional procedures comparing to non-strand-specific mode: 
1. Splitting overlapping genes from different strands
2. Resolving inter-strand repeats
3. Contig output
Thus, I'm a bit puzzled how such results are possible :)

The command and datasets file seem to be fine. Have you tried the latest SPAdes? Not sure it will give different results though..

Could you please contact me by [mail](mailto:andrewprzh@gmail.com) and send me log files from both runs (stranded and non-stranded)? Afterwards, I'll probably need the data to understands the problem.

Best
Andrey
