### ISSUE TITLE
Squeezemeta metatranscriptomics

### ISSUE THREAD

**Issue by seppedm** [ablab/spades#608]
For a metatranscriptomics project I plan to use SPAdes in the SqueezeMeta pipeline. This pipeline has metaSPAdes as its standard method, since it’s a pipeline designed for meta-omics. I was wondering if it would make a big difference if I use metaSPAdes instead of rnaSPAdes, which is recommended in the rnaSPAdes manual. What are the differences and benefits of both methods?
Thanks in advance!!

**Comment by andrewprzh** [comment]
Dear Seppe

Speaking shortly, I'd suggest to use rnaSPAdes for now.

In general, metaSPAdes is designed for assembly of consensus contigs from metagenomic data. rnaSPAdes was developed for eukaryotic transcriptome assembly and aims to reconstruct alternatively spliced isoforms.

Currently, we are working on metatranscriptome assemblies, but don't have full understanding of which tool is better and we don't have any new pipeline yet. Based on what we saw, metaSPAdes gives huge amount of contigs, some of which are quite short and seem like junk. rnaSPAdes seems to have better filtering, but can produce a lot of redundant sequences (especially for rRNA) since it tries to restore all possible "isoforms" from the data. 
Of course, if you have any way to validate the quality, you can try both metaSPAdes and rnaSPAdes, but it will take some time.

If you have any question left, don't hesitate to ask. We are open for further discussions on metatranscriptomes.

Best
Andrey

**Comment by seppedm** [comment]
Dear Andrey,

Thank you for your response. I get the feeling that I get on more places, that metatranscriptomics is a field where there is still a lot to develop and test. For now I don't have any way to validate, so we will have to go with the best guess. 

So if I understand you correctly, this would imply that rnaSPAdes will deliver us more 'correct' sequences, but redundant. Am I correct if I would think that the redundancy is not that much of a problem (apart from increasing computing time) if the goal is to quantify the relative abundance of different functions for example? Since every read will be mapped to only one of the contigs in downstream analysis?

**Comment by andrewprzh** [comment]
> I get the feeling that I get on more places, that metatranscriptomics is a field where there is still a lot to develop and test.
Same feelings, yes.

> Am I correct if I would think that the redundancy is not that much of a problem (apart from increasing computing time) if the goal is to quantify the relative abundance of different functions for example? Since every read will be mapped to only one of the contigs in downstream analysis?

It depends on the mapping software and its parameters. I feel like having a lot of similar sequences for quantification complicates the problem, reads will appear either as multimappers, or will be assigned to an arbitrary sequence.

For example, to evaluate completeness of our metatranscriptome assembly relatively to a database of known proteins, we cluster sequences together before screening them against this database. Since you are interested in quantifying specific functions (rather than individual transcripts from specific strains), similar method may help here to avoid dealing with multimappers. Having a single sequence per gene / function may give more reliable quantification.

> And if this is mostly focussed on eukaryote transcriptomes and splicing, will this have an impact on assembly of prokaryotes?
It's not easy to predict, but I suppose rnaSPAdes can to generate multiple copies of the same gene, especially if it varies across different strains. I don't think that every single nucleotide difference will  lead to creating yet another copy, but more significant variation may. That's what I mostly meant by redundancy.

Best
Andrey

**Comment by seppedm** [comment]
Thank you for the extensive answers. I'm running rnaSPAdes now, and I will see where that gets me. 

Best,
Seppe
