### ISSUE TITLE
Possibilities of Reassembly too many metagenomic NGS-assembled short contigs with metaSpades

### ISSUE THREAD

**Issue by neptuneyt** [ablab/spades#619]
Dear Spades team,
Thanks for your so excellent work first of all. 
 I have 200 Illumina paired-end 150bp metagenomic sequence samples, considering time and calculation reasons, I used megahit to assemble each sample but result to many short contigs 500bp-3000 bp (accounting for > 90% of the total assembly contig numbers) and N50 (just 1000bp).
- Q: so I wonder if metaspades  ```--trusted-contigs``` or ```--untrusted-contigs```can be used to reassemble these short contigs(or combined with longer than 3k long contigs), does it make sense？

Thank you from the bottom of my heart! Looking forward your reply!

**Comment by asl** [comment]
It's perfectly ok to have such number of short contigs for complex metagenomes (depending on the size, coverage, complexity and strain content).

It does not make any sense to "reassemble" these contigs, simply because lots of important information is lost. So, it's likely you'll obtain the similar or even worse results. They could be used to supplement the existing assembly though.
