### ISSUE TITLE
rnaSPAdes read error correction

### ISSUE THREAD

**Issue by seppedm** [ablab/spades#626]
Dear developers,

I noticed that in v3.14.1, read error correction has been turned off for rnaspades. 
- What is the reason for this? To account for subtle variants in transcripts?
- Can samples assembled with older versions (v3.11.1) which include read error correction safely be compared to samples assembled without this? (think soil sample metatranscriptome)

Thanks! 
Seppe

**Comment by andrewprzh** [comment]
Dear Seppe

The story started when reviewers asked us why do we use error correction for RNA assembly, so we decided to test it. It appeared that in this particular case, it doesn't give any significant benefits (if not vise versa), but takes a lot of computational time.

I cannot say for sure about variants since rnaSPAdes removes most of the bulges, caused single-nucleotide difference, but we have seen cases when BayesHammer does overcorrection in high-covered regions.

Regarding comparison, I'd say yes, it is safe. I'd expect better overall assembly quality from newer version, but cannot be 100% sure about metaRNA data. Indeed, 3.11.1 may possible give a better per base accuracy, but I doubt it will be significant.

Best
Andrey
