### ISSUE TITLE
Noticing meta option is producing better assemblies than isolate option on WGS samples - Is this normal?

### ISSUE THREAD

**Issue by slvrshot** [ablab/spades#691]
I have some around 500 'pure' bacterial isolates that were sequenced on an Illumina MiSeq (paired-end reads). The genome size is roughly 2.2MB. I discovered that I accidentally forgot to change the option from 'meta' to 'isolate' in SPAdes (3.14) after a metagenomics project. I proceeded to run the samples in 'isolate' mode and compared the two assembly runs. Quality seems comparable but the 'meta' option seems to have produced better assemblies with fewer contigs on average. Is this normal, should I be concerned? Are there situations where 'meta' is better even though technically these are not metagenomes? Thanks ablab!

**Comment by asl** [comment]
I really do not know which textbook contains this common misbelief that "lower number of contigs => better assembly" (similar to comparing N50 for assemblies of different length). It's not quite so! Fewer contigs could mean anything, including e.g. collapsed inexact repeats, local misassemblies, collapsed variation, etc. metaSPAdes aims for consensus assembly of multiple strains, and therefore contains several aggressive heuristics in order to achieve so. So, it could easily collapse some inexact repeats (as it might be tricky to distinguish variation across species with inexact repeats), etc.

So, unless you're having some other ways of checking the things, I would suggest to stick to the defaults :)
