### ISSUE TITLE
5 similar samples assembly with only 1 error of memory allocation

### ISSUE THREAD

**Issue by EmmettPeng** [ablab/spades#710]
Hi SPAdes team!

Thanks for making this great tool! I was using metaSPAdes on my 5 group of environmental samples of metagenome sequence data while the assembly of four of them was successfully finished but only one failed with
```
mimalloc: error: unable to allocate OS memory (4194304 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)
mimalloc: process info:
   elapsed:   39849.127 s
   process: user: 1235207.133 s, system: 35368.007 s, faults: 1471
       rss: current: 837366575104, peak: 820219326464
    commit: current: 837366575104, peak: 837404323840


== Error ==  system call for: "['/clusterfs/node2/fengkai/pengxi/software/SPAdes-3.15.2-Linux/bin/spades-core', '/clusterfs/node2/fengkai/pengxi/coldseep/layer/metaspades/HMd/K55/configs/config.info', '/clusterfs/node2/fengkai/pengxi/coldseep/layer/metaspades/HMd/K55/configs/mda_mode.info', '/clusterfs/node2/fengkai/pengxi/coldseep/layer/metaspades/HMd/K55/configs/meta_mode.info']" finished abnormally, OS return value: -6
```

I ran this program on cluster with PBS job submission system. I used our best node with 3Tb RAM and 160 processors but it still reported error on this sample. Here is my log file and parameter file. Maybe should I change some params? I really need to finish this assembly soon so your help would be greatly appreciated. 

[params.txt](https://github.com/ablab/spades/files/6293484/params.txt)
[spades.log](https://github.com/ablab/spades/files/6293485/spades.log)

Emmett

**Comment by asl** [comment]
Well, you specified the memory limit (`-m` option) to be 1Tb, so this might limit the amount of RAM available to SPAdes (however, at the time of crash SPAdes used ~800 Gb of RAM and your system failed to fulfil its request to allocate 4M more)

**Comment by EmmettPeng** [comment]
> Well, you specified the memory limit (`-m` option) to be 1Tb, so this might limit the amount of RAM available to SPAdes (however, at the time of crash SPAdes used ~800 Gb of RAM and your system failed to fulfil its request to allocate 4M more)

Thanks for your reply. I reran the command with setting the memoty limit to 4096 but it still failed.

[spades.log](https://github.com/ablab/spades/files/6304982/spades.log)
[params.txt](https://github.com/ablab/spades/files/6304983/params.txt)

I am not sure if it relates to the cluster settings.

**Comment by asl** [comment]
At the time of crash SPAdes consumed ~800 Gb of RAM and your OS failed to fulfil SPAdes request to allocate 4M more.

**Comment by lonestarling** [comment]
hello  EmmettPeng

i have also meet the same error as yours, so have you ever solve this problem.

**Comment by hjruscheweyh** [comment]
Hi @EmmettPeng @lonestarling 

I have the same issue when using version 3.15.2 on a large dataset (#871). It also dies at around 800GB of RAM even though there is >1TB of free RAM left. @asl says that this could be due to a misconfiguration of the server. Does anyone of you know what setting that could be? 

However, I find it strange that this issue appears on 3 different systems and all at ~800GB. Its definitely worth looking into this issue(s), regardless of what the cause is. 

I'm currently rerunning my assembly with an older version of spades (3.14.1) to see whether the error persists.


Best,
Hans

**Comment by lonestarling** [comment]
Hi
i haven't solve this problem yet, even though i set larger RAM as you say. it seems like that the spades was not friendly to be big sequence data. i will appreciate if you tell me when figure it out .

Best
lonestarling



At 2021-11-10 15:24:53, "Hans-Joachim Ruscheweyh" ***@***.***> wrote:

Hi @***@***.***

I have the same issue when using version 3.15.2 on a large dataset (#871). It also dies at around 800GB of RAM even though there is >1TB of free RAM left. @asl says that this could be due to a misconfiguration of the server. Does anyone of you know what setting that could be?

However, I find it strange that this issue appears on 3 different systems and all at ~800GB. Its definitely worth looking into this issue(s), regardless of what the cause is.

I'm currently rerunning my assembly with an older version of spades (3.14.1) to see whether the error persists.

Best,
Hans

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hjruscheweyh** [comment]
Hi @lonestarling 

@asl had an idea to change a configuration setting of the server. I will try that now and report back in the other issue.

Best,
Hans

**Comment by hjruscheweyh** [comment]
@lonestarling It seems that a config change on the server settings has done the trick. Do you want to try your luck too and see if that resolves your issue?

**Comment by lonestarling** [comment]
HI
I am so excited your have resolve this issue, can you describe it in detail，it should be setted with rights of administrator ？ and what the parameter of config should be setting？
appreciate it
best wishes
lonestarling



At 2021-11-13 15:25:50, "Hans-Joachim Ruscheweyh" ***@***.***> wrote:

@lonestarling It seems that a config change on the server settings has done the trick. Do you want to try your luck too and see if that resolves your issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hjruscheweyh** [comment]
I hope that, as this issue will affect other users with deeply sequenced and complex samples, @asl will give a recommendation how to handle these samples in general. Maybe there is a more elegant way compared to using a `sudo` command?

**Comment by asl** [comment]
This is a common and very huge problem: servers are misconfigured (or rather – not configured at all). Just adding 1-2-10 Tb of RAM does not mean that this amount of RAM could be used efficiently as there are lots of other Linux settings that affect the memory allocation. Usually none of these settings are tuned and none of these limits are raised. As a result we're ending with the server with lots of RAM but with thresholds and limits as on the desktop machine.

**Comment by lonestarling** [comment]
Hi 
Hans
i am so glad you disscus  with me about this issue which cofused me,  I totally agree your opinion,  this issue always affect users with deeply sequenced, although we improved the RAM in code, it's not useful yet.  
how much your sequence data? Hans, and what parameters you have changed to solve this issue.
actually i  don't  know how to do a config change on the server setting, perhaps i should tell my administrator. 
sincerely
best wishes










At 2021-11-15 17:19:59, "Hans-Joachim Ruscheweyh" ***@***.***> wrote:

I hope that, as this issue will affect other users with deeply sequenced and complex samples, @asl will give a recommendation how to handle these samples in general. Maybe there is a more elegant way compared to using a sudo command?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lonestarling** [comment]
Waiting for your good news，Hans 


发自我的iPhone

**Comment by lonestarling** [comment]
Waiting for your good news, Hans

发自我的iPhone

> 在 2021年11月15日，下午6:49，陈哲 ***@***.***> 写道：
> 
> ﻿
> Hi 
> Hans
> i am so glad you disscus  with me about this issue which cofused me,  I totally agree your opinion,  this issue always affect users with deeply sequenced, although we improved the RAM in code, it's not useful yet.  
> how much your sequence data? Hans, and what parameters you have changed to solve this issue.
> actually i  don't  know how to do a config change on the server setting, perhaps i should tell my administrator. 
> sincerely
> best wishes
> 
> 
>

**Comment by hjruscheweyh** [comment]
Hi @lonestarling

The sample that broke SPAdes wasn't sequenced too deep (~150 mio) inserts but it was taken from a non-size-filtered marine water sample. So you can expect a large diversity and larger genomes in there which increase the runtime/RAM consumption of SPAdes. 

The issue seems to come from using a default configuration of your system despite being large-RAM server. @asl has recommended to alter the system parameter `sysctl vm.max_map_count=262144`  which solved my issue. This value can/should be set to ~1 per 128KB according to a brief google search. You might want to talk to your sys admin about finding the best fitting value.


Best,
Hans

**Comment by lonestarling** [comment]
Hi @hjruscheweyh 
i haven't figure it out about this "OS return value: -6" issue though i told my  administrator to change the system parameter, i meet the same error  "unable to allocate OS memory (4194304 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)"   ....finished abnormally, OS return value: -6   in the SPAdes-3.15.3.  i am so confused, Hans
Best,
Lonestarling

**Comment by lonestarling** [comment]
@asl i just set my sbatch mem=300GB,   and -m 2000  and i am waiting my final result.    and i'am not sure whether  generate the "OS return value -6"
Best
Lonestarling

**Comment by hjruscheweyh** [comment]
Hi both. Maybe the server was restarted in between? 

I have not seen the issue since updating the system parameter. However I have also not assembled huge datasets since then.

**Comment by asl** [comment]
> I have not seen the issue since updating the system parameter. However I have also not assembled huge datasets since then.

Well, there are two possible issues: inability to obtain free RAM from OS due to exhausted mapping ranges vs lack of free RAM. There is no solution for the second issue besides trying somewhere else, etc. :)

**Comment by lonestarling** [comment]
@asl 
Hi !
asl
after i change my system parameter sysctl vm.max_map_count=262144 , i meet a new errr configs/meta_mode.info']" finished abnormally, OS return value: -9,  i have no ideas, it seems like  the task out of my RAM.    i set my slurem memory 400G,   and set the spade.py -m 2000g. have any advice for me? 
Best
Lonestarling

**Comment by asl** [comment]
@lonestarling No idea as you have not provided your spades.log file. However, your SPAdes job was killed. So, you might want to check with your system administrator what was the reason

**Comment by hjruscheweyh** [comment]
Not a slum user. But my guess is that slurm is killing/limiting your job as you request only 400GB of RAM. I use SGE and LSF and usually request 10% more RAM with the scheduler compared to the RAM requested within spades.

**Comment by lonestarling** [comment]
@asl 
Hi
Here is my spades.log. and i sbatch my job with slurm memory 400G
[spades.log](https://github.com/ablab/spades/files/8107991/spades.log)
@hjruscheweyh 
Hi 
Hans
i totally agree with you, Hans. how about your -m parameter?  the default -m is 250G.
Best
Lonestarling

**Comment by asl** [comment]
@lonestarling Highly likely you've ran out of RAM. It seems you're having very fragmented assembly which demands lots of RAM

**Comment by hjruscheweyh** [comment]
Just set the -m in spades to 2000 and the slurm memory to 2TB and see whether the assembly works. Could also be that you have a huge eukaryotic genome in there? 

If this still breaks consider:
- downsample reads
- read normalisation (bbnorm) --> in a way also downsampling but based on Kmer abundances
- review QC parameters.

**Comment by lonestarling** [comment]
﻿
Waiting for your good news, Hans
发自我的iPhone

**Comment by MeharAsad002** [comment]
I am working on wild soybean Illumina sequenced data, and i am getting the following issues, can anyone please help me solve it? I will attach the file. I have tried reducing number of threads, increasing the RAM and tried on different data set of similar size, but no use. 
[spades.log](https://github.com/user-attachments/files/16808956/spades.log)
