### ISSUE TITLE
Spades remembers --tmp-dir with --continue

### ISSUE THREAD

**Issue by fungs** [ablab/spades#80]
Hi,
when I tried to continue an assembly which was killed on a cluster due to resource limitations, I ran into the issue that the program wanted to continue with the old temporary directory. However, that is usually set to a dynamic path based on the job name, depending on the node it runs on. I had to go through the text files and replace that with a symbolic link pointing to the dynamic tmpdir. It's usually best to use $TMPDIR and fallback /tmp or the functionality provided by POSIX command mktemp to allocate temporary storage. It is easy to overwrite this by a command line parameter or by running `TMPDIR=xyz spades ...`.

Best,
Johannes

**Comment by asl** [comment]
Using $TMDIR or /tmp is not an option – typically it's a small tmpfs-allocated volume that would overflow very soon. The intention of --continue is to indeed continue. Option override is possible via advanced --restart-from interface.

**Comment by fungs** [comment]
> typically it's a small tmpfs-allocated volume

On my DLS router it is, on all our comping nodes it is a couple of terrabytes large. So /tmp should be as large as the requirements are and if it isn't, you need to talk to your sysadmin and you can redirect it. Small in-memory files under Linux go to /dev/shm/. Anyway, I know what you mean. I will try the restart-from option next time, which I have not considered, yet.

Thanks!

**Comment by mmokrejs** [comment]
I do not see this clearly mentioned along advices to use `--continue` , practically `--continue` is useless unless you can ensure job JOB_ID will be same. `--restart-from-interface` needs more thinking from the user and I am not surprised you avoided that. I simply agree with @fungs that spades should not re-use content of `--tmpdir` value.

**Comment by asl** [comment]
@fungs Sadly, as our experience shows SPAdes users run SPAdes in the variety of different environments and the majority of them are different from our cluster's computation nodes. We cannot expect that there is plenty of space in /tmp. And overflowed /tmp might be a nightmare to deal with.

@mmokrejs SPAdes does not reuse the contents of scratch directory. All the checkpoints, etc. are in the project directory

**Comment by mmokrejs** [comment]
> SPAdes does not reuse the contents of scratch directory. All the checkpoints, etc. are in the project directory

? My `$PBS_JOBID` is always different. Let's assume I ran `spades.py --tmp-dir /ramdisk/$PBS_JOBID ...`previously. If I read the original posting correctly then `--continue` results in spades anticipating `/ramdisk/$PBS_JOBID` to still exist, which is wrong. That directory is created for every cluster job during its startup (a random name), and zapped after job exit. Then I understand spades.py fallbacked to elsewhere because it could not find the directory anymore. There used to be a consensus that user apps should use `/var/tmp` instead of `/tmp`. These days I would agree spades.py could sniff out any /dev/shm mountpoint and use it (for the fallback solution). Or at least stick to `/var/tmp`. Either way, `--continue` should ignore past value of `--tmp-dir` IMHO.

**Comment by fungs** [comment]
`--continue` will simply fail because it does not find the temporary directory. I think it was not possible to combine it with `--tmp-dir` to continue with a different location. That at least could be fixed, I guess.

**Comment by asl** [comment]
@fungs We are considering if we could fix at least this for some next SPAdes releases.

**Comment by asl** [comment]
--restart-from / --continue was redone in SPAdes 3.12
