### ISSUE TITLE
Problems with phage assembly

### ISSUE THREAD

**Issue by fetyj** [ablab/spades#95]
Hi,
I'm using Spades for de novo assembly of bacteriophages genome, the software is doing great and almost all of my data gives a circular graph as seen in bandage. The problem is I have noticed that on the  beginning and the end of all my sequences, a repeat of 127 nt is present. For some genome I have partial sequence with sanger so I'm sure there is no such repeat in my genome.
Could anyone explain why and how can I avoid this?

Thanks for any help :)

Cheers,
Fety

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

Sadly we cannot say anything for sure without seeing the data...

**Comment by fetyj** [comment]
Please find in attachment one sample of the data: it contains 2 bacteriophages as expected but each sequence contain the 127nt repeat in extremities  

Cheers,
Fety
[phi_R1.fastq.gz](https://github.com/ablab/spades/files/1883765/phi_R1.fastq.gz)
[phi_R2.fastq.gz](https://github.com/ablab/spades/files/1883766/phi_R2.fastq.gz)

**Comment by snurk** [comment]
Dear @fetyj 
It is due to the properties of de Bruijn graphs that SPAdes uses.
Sequences incident to the same vertex in Bandage will always have overlap of the size equal to the last used value of parameter K (127 in your case).
Feel free to remove it after checking that the contig is circular in Bandage.
--
Best,
Sergey

**Comment by fetyj** [comment]
Thanks for the help.
Cheers,
Fety
